feat: add matches service logic
ITMO-TECH-TEAM-3/TEAM-3-3 pull request #44
Opened 2022-06-25 18:53 UTC by mullerdaniil

2022-06-25 19:50 UTC, Strong-Wings approved these changes

2022-06-25 19:50 UTC, soldey requested changes

2022-06-25 19:50 UTC, soldey commented on src/main/java/com/tech/tournaments/service/impl/MatchServiceImpl.java
> +            LOG.error("Failed to create tournament: {}", e.getMessage());
failed to create match

2022-06-26 08:06 UTC, soldey approved these changes

2022-06-26 08:06 UTC, merged